# Generated by Django 5.1 on 2024-09-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_enrollment_duedate_enrollment_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='Gender',
            field=models.CharField(default='Male', max_length=25),
        ),
    ]
